### ISSUE TITLE
Ubuntu/production error

### ISSUE THREAD

**Issue by NetOpWibby** [MarkTiedemann/deno-dart-sass#2]
I'm trying to use this on a server and running into an issue:

```
error: Uncaught (in promise) NotFound: No such file or directory (os error 2), rename './dart-sass/src/dart' -> './dart'
			await Promise.all([
			^
    at async Object.rename (deno:runtime/js/30_fs.js:174:5)
    at async Promise.all (index 0)
    at async renameFiles (https://raw.githubusercontent.com/MarkTiedemann/deno-dart-sass/0.2.0/mod.ts:324:4)
    at async useDartSass (https://raw.githubusercontent.com/MarkTiedemann/deno-dart-sass/0.2.0/mod.ts:141:3)
    at async file:///var/www/sld/neuenet/blog/main.ts:34:18
```

I probably shouldn't be compiling stuff on a server but YOLO, laziness. In the short-term, I'll detect if I'm working locally and if so, run Sass compilation.

**Comment by MarkTiedemann** [comment]
@NetOpWibby Thanks for the bug report!

I investigated and found the underlying error:

The dart-sass Linux archives, contrary to the Windows and MacOS archives, contain a native sass executable rather than a dart executable plus sass snapshot.

Hence, the logic needs to be adjusted for Linux.

Will release a fix soon.

**Comment by MarkTiedemann** [comment]
@NetOpWibby Just released a fix: https://github.com/MarkTiedemann/deno-dart-sass/commit/44a0b44687f9a868f686e8b8c012197e861ca7d2

Can you test it? I currently don't have a Linux machine which I could use for testing.

**Comment by NetOpWibby** [comment]
Nice, it works!

**Comment by MarkTiedemann** [comment]
Thanks for testing!
